- id: '1740934865907'
  alias: Close_all_shutters_button
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_button.close_all_shutters
  conditions: []
  actions:
  - device_id: 29585a20f3fbfca630b76000634c3721
    domain: cover
    entity_id: 0c96a91d637786de9c3c4b8c62e2cd15
    type: close
  - device_id: d9e4760c6804abf6a242478997af1bc9
    domain: cover
    entity_id: c38762c4e1346aee1d8da7c557e4fc4d
    type: close
  - device_id: 1122cfe945db9a3e5d311d013cbd3838
    domain: cover
    entity_id: 10c7f235622ae3fc590fb3939f37b588
    type: close
  - device_id: a5a47a3e4fb130e79b276d2521246d65
    domain: cover
    entity_id: a9218af01b32e2c4452adab3335af7ae
    type: close
  - device_id: 127e03e673af450119261632ec6cf656
    domain: cover
    entity_id: 10b3280200df150e04e924b97603d33c
    type: close
  - device_id: 27f60140f2cdc08645bbb7c3f027bbfc
    domain: cover
    entity_id: 4e8919b11b6f79b5c3638560f1249238
    type: close
  mode: single
- id: '1740944003530'
  alias: Open all shutters
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_button.open_all_shutters
  conditions: []
  actions:
  - device_id: 29585a20f3fbfca630b76000634c3721
    domain: cover
    entity_id: 0c96a91d637786de9c3c4b8c62e2cd15
    type: open
  - device_id: 1122cfe945db9a3e5d311d013cbd3838
    domain: cover
    entity_id: 10c7f235622ae3fc590fb3939f37b588
    type: open
  - device_id: d9e4760c6804abf6a242478997af1bc9
    domain: cover
    entity_id: c38762c4e1346aee1d8da7c557e4fc4d
    type: open
  - device_id: a5a47a3e4fb130e79b276d2521246d65
    domain: cover
    entity_id: a9218af01b32e2c4452adab3335af7ae
    type: open
  - device_id: 127e03e673af450119261632ec6cf656
    domain: cover
    entity_id: 10b3280200df150e04e924b97603d33c
    type: open
  - device_id: 27f60140f2cdc08645bbb7c3f027bbfc
    domain: cover
    entity_id: 4e8919b11b6f79b5c3638560f1249238
    type: open
  mode: single
- id: '1749370546626'
  alias: PAC_SALON_COOL_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: hvac_mode_changed
    trigger: device
    to: heat
  conditions:
  - condition: device
    device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: is_hvac_mode
    hvac_mode: cool
  actions:
  - device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370614163'
  alias: PAC_SALON_HEAT_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: hvac_mode_changed
    trigger: device
    to: cool
  conditions:
  - condition: device
    device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: is_hvac_mode
    hvac_mode: heat
  actions:
  - device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370725837'
  alias: PAC_SALLE_MANGER_COOL_SET_OFF_IF_CONFLICT
  description: ''
  triggers:
  - device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: hvac_mode_changed
    trigger: device
    to: heat
  conditions:
  - condition: device
    device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: is_hvac_mode
    hvac_mode: cool
  actions:
  - device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370758433'
  alias: PAC_SALLE_MANGER_HEAT_SET_OFF_IF_CONFLICT
  description: ''
  triggers:
  - device_id: df884e8b3a38d48928db48632ca261d5
    domain: climate
    entity_id: 06115d7e02e5b698aca583b5bc55c80c
    type: hvac_mode_changed
    trigger: device
    to: cool
  conditions:
  - condition: device
    device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: is_hvac_mode
    hvac_mode: heat
  actions:
  - device_id: 67aaea08a8beea65f80059603f90be89
    domain: climate
    entity_id: 19db94019cf042f5f940fafebe0a8aef
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370855349'
  alias: PAC_PETITE_CHAMBRE_HEAT_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: hvac_mode_changed
    trigger: device
    to: cool
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: hvac_mode_changed
    trigger: device
    to: cool
  conditions:
  - condition: device
    device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: is_hvac_mode
    hvac_mode: heat
  actions:
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370896277'
  alias: PAC_PETITE_CHAMBRE_COOL_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: hvac_mode_changed
    trigger: device
    to: heat
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: hvac_mode_changed
    trigger: device
    to: heat
  conditions:
  - condition: device
    device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: is_hvac_mode
    hvac_mode: cool
  actions:
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749370992895'
  alias: PAC_GRANDE_CHAMBRE_COOL_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: hvac_mode_changed
    trigger: device
    to: heat
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: hvac_mode_changed
    trigger: device
    to: heat
  conditions:
  - condition: device
    device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: is_hvac_mode
    hvac_mode: cool
  actions:
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749371023228'
  alias: PAC_GRANDE_CHAMBRE_HEAT_SET_OFF_ON_CONFLICT
  description: ''
  triggers:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: hvac_mode_changed
    trigger: device
    to: cool
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: hvac_mode_changed
    trigger: device
    to: cool
  conditions:
  - condition: device
    device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: is_hvac_mode
    hvac_mode: heat
  actions:
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749371161071'
  alias: PAC_COMBLES_SET_OFF_ON_CONFLICT_COOL
  description: ''
  triggers:
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: hvac_mode_changed
    trigger: device
    to: cool
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: hvac_mode_changed
    trigger: device
    to: cool
  conditions:
  - condition: not
    conditions:
    - condition: device
      device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
      domain: climate
      entity_id: ca4a9c3089608882de700c2a6f011734
      type: is_hvac_mode
      hvac_mode: cool
  actions:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1749371227980'
  alias: PAC_COMBLES_SET_OFF_ON_CONFLICT_HEAT
  description: ''
  triggers:
  - device_id: e8ceabf3c7728862a264a511a8f6f6cd
    domain: climate
    entity_id: eb64c5e3a2a7e357c26516c12aaaa427
    type: hvac_mode_changed
    trigger: device
    to: heat
  - device_id: 7f7757cb536520e3fa1df8a52d77e183
    domain: climate
    entity_id: 7d3aeab8a3d1df9509bb300ea9c2d87f
    type: hvac_mode_changed
    trigger: device
    to: heat
  conditions:
  - condition: not
    conditions:
    - condition: device
      device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
      domain: climate
      entity_id: ca4a9c3089608882de700c2a6f011734
      type: is_hvac_mode
      hvac_mode: heat
  actions:
  - device_id: 7a35b24e16cd75c69531d6ef8c7a2d0c
    domain: climate
    entity_id: ca4a9c3089608882de700c2a6f011734
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1757855102773'
  alias: Switch buanderie prise 1 on others off
  description: ''
  triggers:
  - type: turned_on
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 118bca50ee3747d4a6cdcd47d5578639
    domain: switch
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 557b91e54b86ec02cce325c44e1484f6
    domain: switch
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 89c663d6b1de5b7ed6dc09e867bb4f1f
    domain: switch
  mode: single
- id: '1757855845658'
  alias: Switch buanderie on prise 2 on others off
  description: ''
  triggers:
  - type: turned_on
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 557b91e54b86ec02cce325c44e1484f6
    domain: switch
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 118bca50ee3747d4a6cdcd47d5578639
    domain: switch
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 89c663d6b1de5b7ed6dc09e867bb4f1f
    domain: switch
  mode: single
- id: '1757856774418'
  alias: Switch bouanderie on radiateurs on others off
  description: ''
  triggers:
  - type: turned_on
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 89c663d6b1de5b7ed6dc09e867bb4f1f
    domain: switch
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 557b91e54b86ec02cce325c44e1484f6
    domain: switch
  - type: turn_off
    device_id: a4ac1c53348f2bcd82d2a2c9bd59707a
    entity_id: 118bca50ee3747d4a6cdcd47d5578639
    domain: switch
  mode: single
