# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation yaml: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages

mqtt:
  # PAC salon -------------------------------------------
  - climate:
      unique_id: pac_salon
      name: pac_salon
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffe5bbc77
        name: pac/bas/salon
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/bas/salon
      fan_mode_command_topic: zigbee2mqtt/pac/bas/salon/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/bas/salon
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/bas/salon/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/bas/salon
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/bas/salon/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/bas/salon/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open

      temperature_high_command_topic: zigbee2mqtt/pac/bas/salon/set/occupied_cooling_setpoint
      temperature_low_command_topic: zigbee2mqtt/pac/bas/salon/set/occupied_heating_setpoint

      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/bas/salon
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/bas/salon

      mode_command_topic: zigbee2mqtt/pac/bas/salon/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/bas/salon
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16

  # PAC salle à manger -------------------------------------------
  - climate:
      unique_id: pac_salle_manger
      name: pac_salle_manger
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffec27130
        name: pac/bas/salle_manger
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/bas/salle_manger
      fan_mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/bas/salle_manger/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/bas/salle_manger/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open
      temperature_high_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/occupied_cooling_setpoint
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/bas/salle_manger
      temperature_low_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/occupied_heating_setpoint
      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/bas/salle_manger
      mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16