# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  # PAC salon -------------------------------------------
  - climate:
      unique_id: pac_salon
      name: pac_salon
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffe5bbc77
        name: pac/bas/salon
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/bas/salon
      fan_mode_command_topic: zigbee2mqtt/pac/bas/salon/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/bas/salon
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/bas/salon/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/bas/salon
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/bas/salon/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/bas/salon/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open

      temperature_high_command_topic: zigbee2mqtt/pac/bas/salon/set/occupied_cooling_setpoint
      temperature_low_command_topic: zigbee2mqtt/pac/bas/salon/set/occupied_heating_setpoint

      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/bas/salon
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/bas/salon

      mode_command_topic: zigbee2mqtt/pac/bas/salon/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/bas/salon
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16

  # PAC salle à manger -------------------------------------------
  - climate:
      unique_id: pac_salle_manger
      name: pac_salle_manger
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffec27130
        name: pac/bas/salle_manger
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/bas/salle_manger
      fan_mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/bas/salle_manger/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/bas/salle_manger/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open
      temperature_high_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/occupied_cooling_setpoint
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/bas/salle_manger
      temperature_low_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/occupied_heating_setpoint
      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/bas/salle_manger
      mode_command_topic: zigbee2mqtt/pac/bas/salle_manger/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/bas/salle_manger
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16

  # PAC grande chambre -------------------------------------------
  - sensor:
      unique_id: pac_grande_chambre_temperature_set_heat
      name: "Temperature set pac grande chambre heat"
      state_topic: "homeassistant/climate/haut/grande_chambre/temperature/heat/set"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"
  - sensor:
      unique_id: pac_grande_chambre_temperature_set_cool
      name: "Temperature set pac grande chambre cool"
      state_topic: "homeassistant/climate/haut/grande_chambre/temperature/cool/set"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"
  - sensor:
      unique_id: pac_grande_chambre_temperature_device_heat
      name: "Temperature real pac grande chambre heat"
      state_topic: "zigbee2mqtt/pac/haut/grande_chambre/set/occupied_heating_setpoint"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"
  - sensor:
      unique_id: pac_grande_chambre_temperature_device_cool
      name: "Temperature real pac grande chambre cool"
      state_topic: "zigbee2mqtt/pac/haut/grande_chambre/set/occupied_cooling_setpoint"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"
  - sensor:
      unique_id: pac_grande_chambre_temperature_diff
      name: "Temperature diff pac grande chambre"
      state_topic: "homeassistant/climate/haut/grande_chambre/temperature/diff/set"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"

  - climate:
      unique_id: pac_grande_chambre
      name: pac_grande_chambre
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffeb33fd1
        name: pac/haut/grande_chambre
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/haut/grande_chambre
      fan_mode_command_topic: zigbee2mqtt/pac/haut/grande_chambre/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/haut/grande_chambre
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/haut/grande_chambre/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/haut/grande_chambre
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/haut/grande_chambre/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/haut/grande_chambre/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open

      #temperature_high_command_topic: zigbee2mqtt/pac/haut/grande_chambre/set/occupied_cooling_setpoint
      #temperature_low_command_topic: zigbee2mqtt/pac/haut/grande_chambre/set/occupied_heating_setpoint

      temperature_high_command_topic: homeassistant/climate/haut/grande_chambre/temperature/cool/set
      temperature_low_command_topic: homeassistant/climate/haut/grande_chambre/temperature/heat/set

      #temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      #temperature_high_state_topic: zigbee2mqtt/pac/haut/grande_chambre
      #temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      #temperature_low_state_topic: zigbee2mqtt/pac/haut/grande_chambre

      temperature_high_state_topic: "homeassistant/climate/haut/grande_chambre/temperature/cool/set/hvac_interface"
      temperature_low_state_topic: "homeassistant/climate/haut/grande_chambre/temperature/heat/set/hvac_interface"

      mode_command_topic: zigbee2mqtt/pac/haut/grande_chambre/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/haut/grande_chambre
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16

  # PAC petite chambre -------------------------------------------
  - climate:
      unique_id: pac_petite_chambre
      name: pac_petite_chambre
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffeb330df
        name: pac/haut/petite_chambre
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/haut/petite_chambre
      fan_mode_command_topic: zigbee2mqtt/pac/haut/petite_chambre/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/haut/petite_chambre
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/haut/petite_chambre/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/haut/petite_chambre
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/haut/petite_chambre/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/haut/petite_chambre/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open
      temperature_high_command_topic: zigbee2mqtt/pac/haut/petite_chambre/set/occupied_cooling_setpoint
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/haut/petite_chambre
      temperature_low_command_topic: zigbee2mqtt/pac/haut/petite_chambre/set/occupied_heating_setpoint
      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/haut/petite_chambre
      mode_command_topic: zigbee2mqtt/pac/haut/petite_chambre/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/haut/petite_chambre
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16

  # PAC combles -------------------------------------------
  - climate:
      unique_id: pac_combles
      name: pac_combles
      device:
        identifiers:
          - zigbee2mqtt_0x5cc7c1fffed9600c
        name: pac/haut/combles
      availability:
        - topic: zigbee2mqtt/bridge/state
          value_template: "{{ value_json.state }}"
      current_temperature_template: "{{ value_json.local_temperature }}"
      current_temperature_topic: zigbee2mqtt/pac/haut/combles
      fan_mode_command_topic: zigbee2mqtt/pac/haut/combles/set/fan_mode
      fan_mode_state_template: "{{ value_json.fan_mode }}"
      fan_mode_state_topic: zigbee2mqtt/pac/haut/combles
      fan_modes:
        - low
        - medium
        - high
        - auto
      preset_mode_command_topic: zigbee2mqtt/pac/haut/combles/set/preset
      preset_mode_state_topic: zigbee2mqtt/pac/haut/combles
      preset_mode_value_template: "{{ value_json.preset }}"
      preset_modes:
        - activity
        - boost
        - eco
      swing_mode_command_topic: homeassistant/climate/haut/combles/extended_fan/set
      swing_mode_state_topic: homeassistant/climate/haut/combles/extended_fan
      swing_modes:
        - swing
        - quarter_open
        - half_open
        - three_quarters_open
        - fully_open
      temperature_high_command_topic: zigbee2mqtt/pac/haut/combles/set/occupied_cooling_setpoint
      temperature_high_state_template: "{{ value_json.occupied_cooling_setpoint }}"
      temperature_high_state_topic: zigbee2mqtt/pac/haut/combles
      temperature_low_command_topic: zigbee2mqtt/pac/haut/combles/set/occupied_heating_setpoint
      temperature_low_state_template: "{{ value_json.occupied_heating_setpoint }}"
      temperature_low_state_topic: zigbee2mqtt/pac/haut/combles
      mode_command_topic: zigbee2mqtt/pac/haut/combles/set/system_mode
      mode_state_template: "{{ value_json.system_mode }}"
      mode_state_topic: zigbee2mqtt/pac/haut/combles
      modes:
        - "off"
        - heat
        - cool
        - auto
        - dry
        - fan_only
      max_temp: 30
      min_temp: 16
